flat_get_info_chene_truffe.Rmd:
  path: dev/flat_get_info_chene_truffe.Rmd
  state: active
  R:
  - R/get_info.R
  - R/get_info_chene.R
  - R/get_info_chene_last_truffe.R
  - R/get_info_chene_truffe.R
  - R/get_info_reensemence.R
  - R/weight_truffles_by.R
  tests:
  - tests/testthat/test-get_info_chene_truffe.R
  - tests/testthat/test-get_info_reensemence.R
  - tests/testthat/test-get_info_chene.R
  - tests/testthat/test-get_info.R
  - tests/testthat/test-weight_truffles_by.R
  - tests/testthat/test-get_info_chene_last_truffe.R
  vignettes: []
  inflate:
    flat_file: dev/flat_get_info_chene_truffe.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: ask
flat_utils.Rmd:
  path: dev/flat_utils.Rmd
  state: active
  R: R/check_param.R
  tests: []
  vignettes: []
  inflate:
    flat_file: dev/flat_utils.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: ask
flat_utils_db.Rmd:
  path: dev/flat_utils_db.Rmd
  state: active
  R:
  - R/connect_db.R
  - R/update_db_truffe.R
  - R/write_db_new_truffe.R
  tests:
  - tests/testthat/test-connect_db.R
  - tests/testthat/test-write_db_new_truffe.R
  - tests/testthat/test-update_db_truffe.R
  vignettes: []
  inflate:
    flat_file: dev/flat_utils_db.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: ask
flat_utils_js.Rmd:
  path: dev/flat_utils_js.Rmd
  state: active
  R: R/prepare_leaflet.R
  tests: tests/testthat/test-prepare_leaflet.R
  vignettes: []
  inflate:
    flat_file: dev/flat_utils_js.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: ask
