---
title: "flat_utils_db.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# connect_db
    
```{r function-connect_db}
#' connect_db
#' 
#' To connect to the database available in the {truffles} package
#' 
#' @param dbname name of db available in inst/
#' @importFrom RSQLite SQLite
#' @importFrom DBI dbConnect
#' @return NULL
#' 
#' @export
connect_db <- function(dbname = "chenes_truffe.sqlite"){
    conn <- dbConnect(SQLite(), 
                      system.file(dbname, package = "truffles"))
    return(conn)
}
```
  
```{r example-connect_db}
connect_db()
```
  
```{r tests-connect_db}
test_that("connect_db works", {
  conn <- connect_db()

  # Vérifier que la connexion est valide
  expect_s4_class(conn, "SQLiteConnection")
})
```

# write_db_new_truffe
    
```{r function-write_db_new_truffe}
#' Write new truffle data to the database
#' 
#' This function writes new truffle data to the specified database table.
#' 
#' @param conn A connection to the database.
#' @param theidchene The ID of the oak tree (chêne) where the truffle was found.
#' @param date_trouvee The date the truffle was found.
#' @param poids The weight of the truffle in grams.
#' @param estimation logical indicating whether the weight was estimated or not.
#' @param comment Any additional comments related to the truffle.
#' @param digest_ The digest of the truffle.
#'
#' @importFrom digest digest
#' @importFrom DBI dbAppendTable
#' @return NULL
#' 
#' @export
write_db_new_truffe <-
  function(conn = connect_db(), theidchene, date_trouvee, poids, estimation, comment, digest_ = Sys.time()) {
    
  idtruffe = digest(digest_)
    
  add_truffe <- data.frame(
  idtruffe = idtruffe,
  idchene = theidchene,
  date_trouve = as.Date(date_trouvee),
  poids = poids,
  estimation = estimation,
  commentaires = comment
)
  
  dbAppendTable(conn, "truffe", add_truffe)
  message("WRITING in DB truffe")
  }
```
  
```{r example-write_db_new_truffe}
# write_db_new_truffe(theidchene = "chene")
```
  
```{r tests-write_db_new_truffe}
test_that("write_db_new_truffe works", {
  
  conn <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
  
  # Création de la table truffe dans la base de données
  DBI::dbWriteTable(
    conn,
    "truffe",
    data.frame(
      idtruffe = character(),
      idchene = numeric(),
      date_trouve = numeric(),
      poids = numeric(),
      estimation = logical(),
      commentaires = character()
    )
  )
  
  # Écrire une nouvelle truffe dans la base de données
  theidchene <- 1
  date_trouvee <- "2024-03-08"
  poids <- 50
  comment <- "Truffe fraîchement trouvée"
  estimation <- 1
  write_db_new_truffe(conn, theidchene, date_trouvee, poids, estimation, comment, digest_ = date_trouvee)
  
  # Vérifier si la truffe a été correctement ajoutée à la base de données
  expected_output <-
    data.frame(
      idtruffe = digest::digest(date_trouvee),
      idchene = 1,
      date_trouve = 19790,
      poids = 50,
      estimation = 1,
      commentaires = "Truffe fraîchement trouvée"
    )
  expect_equal(DBI::dbReadTable(conn, "truffe"), expected_output)
})
```


# update_db_truffe
    
```{r function-update_db_truffe}
#' Update a row in the "truffe" table of a database.
#'
#' This function updates a row in the "truffe" table of a database using an SQL UPDATE query.
#'
#' @param conn A connection to the database.
#' @param idtruffe The identifier of the truffle to update.
#' @param idchene The identifier of the oak tree associated with the truffle.
#' @param date_trouve The date when the truffle was found.
#' @param poids The weight of the truffle.
#' @param commentaires The comments associated with the truffle.
#' @param estimation The estimation of the truffle.
#'
#' @return The function does not return any value, but it updates the corresponding row in the "truffe" table of the database.
#' @importFrom DBI dbExecute
#' 
#' @export
update_db_truffe <- function(conn = connect_db(), idtruffe, idchene, date_trouve, poids, commentaires, estimation){

# Construire et exécuter la requête SQL pour mettre à jour la ligne
update_query <- paste0("UPDATE truffe",
                      " SET idtruffe = '", idtruffe, "',",
                      " idchene = '", idchene, "',",
                      " date_trouve = ", date_trouve, ",",
                      " poids = ", poids, ",",
                      " commentaires = '", commentaires, "',",
                      " estimation = ", estimation, "",
                      " WHERE idtruffe = '", idtruffe, "'")

DBI::dbExecute(conn, update_query)
message("UPDATE db truffe")
}
```
  
```{r example-update_db_truffe}

conn <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
  
  # Création de la table truffe dans la base de données
  DBI::dbWriteTable(
    conn,
    "truffe",
    data.frame(
      idtruffe = "156",
      idchene = "15",
      date_trouve = as.numeric(as.Date("2020/02/02")),
      poids = 12,
      estimation = 1,
      commentaires = "Comment"
    )
  )

update_db_truffe(conn, idtruffe = "156", idchene = "15", date_trouve = as.numeric(as.Date("2020/02/02")), poids = 22, 
                 estimation = 0, commentaires = "New comment")
```
  
```{r tests-update_db_truffe}
test_that("update_db_truffe works", {
  expect_true(inherits(update_db_truffe, "function")) 

conn <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
  
  # Création de la table truffe dans la base de données
  DBI::dbWriteTable(
    conn,
    "truffe",
    data.frame(
      idtruffe = "156",
      idchene = "15",
      date_trouve = 18294,
      poids = 12,
      estimation = 1,
      commentaires = "Comment"
    )
  )

update_db_truffe(conn, idtruffe = "156", idchene = "15", date_trouve = 18294, poids = 22, 
                 estimation = 0, commentaires = "New comment")

  # Vérifier si la truffe a été correctement ajoutée à la base de données
  expected_output <-
    data.frame(
      idtruffe = "156",
      idchene = "15",
      date_trouve = 18294,
      poids = 22,
      estimation = 0,
      commentaires = "New comment"
    )
  expect_equal(DBI::dbReadTable(conn, "truffe")  |> 
  dplyr::filter(idtruffe == "156"), expected_output)
})
```
  


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_utils_db.Rmd", 
               vignette_name = NA, 
               check = FALSE)
grkstyle::grk_style_pkg()
```
