---
title: "flat_get_info_chene_truffe.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# get_info_chene_truffe

```{r function-get_info_chene_truffe}
#' Get information about truffles associated with an oak tree
#' 
#' This function retrieves information about truffles associated with a specific oak tree
#' based on the oak tree's ID from the provided truffle database.
#' 
#' @param dbtruffe Database containing information about truffles.
#' @param theidchene ID of the oak tree for which information about associated truffles
#' is to be retrieved.
#'
#' @return A list containing information about truffles associated with the oak tree,
#' including the total weight, date of the last truffle found, and any comments.
#' 
#' @importFrom dplyr filter summarise pull
#' @export
#'
#' @examples
get_info_chene_truffe <- function(dbtruffe, theidchene) {

check_param(dbtruffe, "data.frame")
check_param(theidchene, "numeric")
check_names_dataframe(c("idchene", "poids","date_trouve", "commentaires"), dbtruffe)

truffe_chene <- dbtruffe |>
      filter(idchene == theidchene) 

if (nrow(truffe_chene) == 0) {
  return(list(poids_tot = 0,
            derniere_truffe = "-",
            comments = "-"))
}
  
poids_tot = truffe_chene |>
  summarise(poids_tot = sum(poids, na.rm = TRUE)) |> 
  pull(poids_tot)

derniere_truffe <- truffe_chene |>
  summarise(date_trouve = as.Date(max(date_trouve, na.rm = TRUE)))|> 
  pull(date_trouve)

comments <-
  paste(
    paste(
    as.Date(truffe_chene$date_trouve),
    truffe_chene$commentaires,
    sep = " : "
  ),
  collapse = "<br>")

return(list(poids_tot = poids_tot,
            derniere_truffe = derniere_truffe,
            comments = comments))


}
```

```{r examples-get_info_chene_truffe}
conn <- connect_db()
truffe <- DBI::dbReadTable(conn, name = "truffe")

get_info_chene_truffe(dbtruffe = truffe, theidchene = 119)
DBI::dbDisconnect(conn)
```

```{r tests-get_info_chene_truffe}
test_that("get_info_chene_truffe works", {

  
  dbtruffe <- data.frame(
    idchene = c(1, 1, 2, 3, 3),
    poids = c(100, 150, 200, 50, 75),
    date_trouve = c(
      "2024-01-01",
      "2024-02-01",
      "2024-03-01",
      "2024-04-01",
      "2024-05-01"
    ),
    commentaires = c(
      "Belle truffe",
      "Truffe exceptionnelle",
      "Truffe moyenne",
      "Truffe petite",
      "Truffe moyenne"
    )
  )
  
  # Test quand le chêne n'existe pas dans la base de données
  expect_equal(
    get_info_chene_truffe(dbtruffe, 4),
    list(
      poids_tot = 0,
      derniere_truffe = "-",
      comments = "-"
    )
  )
  
  # Test quand le chêne existe dans la base de données
  expected_output <-
    list(
      poids_tot = 125,
      derniere_truffe = as.Date("2024-05-01"),
      comments = "2024-04-01 : Truffe petite<br>2024-05-01 : Truffe moyenne"
    )
  
  expect_equal(get_info_chene_truffe(dbtruffe, 3), expected_output)
  
  
})
```



# get_info_chene
    
```{r function-get_info_chene}
#' Get information about an oak tree
#' 
#' This function retrieves information about a specific oak tree based on its ID
#' from the provided oak tree database.
#' 
#' @param dbchene Database containing information about oak trees.
#' @param theidchene ID of the oak tree for which information is to be retrieved.
#'
#' @return A list containing information about the oak tree, including its type and
#' date of plantation.
#'
#' @importFrom dplyr filter 
#' @return a list
#' 
#' @export
get_info_chene <- function(dbchene, theidchene){

check_param(dbchene, "data.frame")
check_param(theidchene, "numeric")
check_names_dataframe(c("id", "type","date_plantation"), dbchene)

  chene <- dbchene |>
      filter(id == theidchene) 
    
    return(list(type = chene$type,
            date_plantation = as.Date(chene$date_plantation)))


}
```
  
```{r example-get_info_chene}
conn <- DBI::dbConnect(RSQLite::SQLite(), system.file("chenes_truffe.sqlite", package = "truffles"))
chene <- DBI::dbReadTable(conn, name = "chenes_feularde")

get_info_chene(dbchene = chene, theidchene = 162)
DBI::dbDisconnect(conn)


```
  
```{r tests-get_info_chene}
test_that("get_info_chene works", {
  
  
  dbchene <- data.frame(
    id = c(1, 2, 3),
    type = c("Chêne vert", "Chêne rouvre", "Chêne pédonculé"),
    date_plantation = c("2020-01-01", "2018-03-15", "2019-06-20")
  )
  
  # Test quand le chêne n'existe pas dans la base de données
  expect_equal(get_info_chene(dbchene, 4),
               list(
                 type = character(0),
                 date_plantation = structure(numeric(0), class = "Date")
               ))
  
  # Test quand le chêne existe dans la base de données
  expect_equal(get_info_chene(dbchene, 2),
               list(type = "Chêne rouvre", date_plantation = as.Date("2018-03-15")))
  
  expect_error(get_info_chene(iris, 2))
  
  expect_error(get_info_chene(iris, mtcars), regexp = "theidchene must be a numeric")

})
```
  
# get_info
    
```{r function-get_info}
#' Get information about oak and truffles
#' 
#' This function retrieves information about oak trees and truffles based on the provided
#' databases and oak tree ID.
#' 
#' @param dbchene Database containing information about oak trees.
#' @param dbtruffe Database containing information about truffles.
#' @param theidchene ID of the oak tree for which information is to be retrieved.
#'
#' @return A list containing information about oak trees and truffles.
#' 
#' 
#' @export
get_info <- function(dbchene, dbtruffe, theidchene){

    resultat <- list(
      chene = get_info_chene(dbchene = dbchene, theidchene = theidchene),
      truffes = get_info_chene_truffe(dbtruffe = dbtruffe, theidchene = theidchene)
    )
    
    return(resultat)
}
```
  
```{r example-get_info}
conn <- DBI::dbConnect(RSQLite::SQLite(), system.file("chenes_truffe.sqlite", package = "truffles"))
chene <- DBI::dbReadTable(conn, name = "chenes_feularde")
truffe <- DBI::dbReadTable(conn, name = "truffe")

get_info(dbchene = chene, dbtruffe = truffe, theidchene = 162)
DBI::dbDisconnect(conn)
```
  
```{r tests-get_info}
test_that("get_info works", {
  # Création de données de test
  dbchene <- data.frame(
    id = c(1, 2, 3),
    type = c("Chêne vert", "Chêne rouvre", "Chêne pédonculé"),
    date_plantation = c("2020-01-01", "2018-03-15", "2019-06-20")
  )
  
  dbtruffe <- data.frame(
    idchene = c(1, 1, 2, 3, 3),
    poids = c(100, 150, 200, 50, 75),
    date_trouve = c(
      "2024-01-01",
      "2024-02-01",
      "2024-03-01",
      "2024-04-01",
      "2024-05-01"
    ),
    commentaires = c(
      "Belle truffe",
      "Truffe exceptionnelle",
      "Truffe moyenne",
      "Truffe petite",
      "Truffe moyenne"
    )
  )
  
  # Test quand le chêne n'existe pas dans la base de données
  expect_equal(get_info(dbchene, dbtruffe, 4),
               list(
                 chene = list(
                   type = character(0),
                   date_plantation = structure(numeric(0), class = "Date")
                 ),
                 truffes = list(
                   poids_tot = 0,
                   derniere_truffe = "-",
                   comments = "-"
                 )
               ))
  
  # Test quand le chêne existe dans la base de données
  expected_output <-
    list(
      chene = list(
        type = "Chêne pédonculé",
        date_plantation = structure(18067, class = "Date")
      ),
      truffes = list(
        poids_tot = 125,
        derniere_truffe = structure(19844, class = "Date"),
        comments = "2024-04-01 : Truffe petite<br>2024-05-01 : Truffe moyenne"
      )
    )
  expect_equal(get_info(dbchene, dbtruffe, 3), expected_output)
})
```
  
# weight_truffles_by
    
```{r function-weight_truffles_by}
#' Calculate total weight of truffles grouped by specified columns
#'
#' This function calculates the total weight of truffles grouped by specified columns
#' in a given data frame.
#'
#' @param dbtruffe A data frame containing information about truffles.
#' @param ... Columns to group by, passed as arguments.
#'
#' @return A summarized data frame containing the total weight of truffles
#' grouped by the specified columns.
#' @importFrom dplyr mutate group_by summarise
#' @importFrom lubridate year
#' @export
weight_truffles_by <- function(dbtruffe, ...) {

check_param(dbtruffe, "data.frame")
check_names_dataframe(c("poids"), dbtruffe)

  dbtruffe |> 
    group_by(...) |> 
    summarise(poids = sum(poids, na.rm = TRUE), .groups = "drop")
}
```
  
```{r example-weight_truffles_by}

library(dplyr)

conn <- connect_db()
truffes <- DBI::dbReadTable(conn, name = "truffe")

weight_truffles_by(truffes, annee = lubridate::year(as.Date(date_trouve)))

truffes_chene <- truffes |> 
  inner_join(DBI::dbReadTable(conn, name = "chenes_feularde"), by = join_by(idchene == id))
weight_truffles_by(truffes_chene, annee = lubridate::year(as.Date(date_trouve)), type)
```
  
```{r tests-weight_truffles_by}
test_that("weight_truffles_by works", {
truffles <- data.frame(
  idchene = c(1, 1, 2, 2, 3, 3),
  poids = c(100, 150, 200, 250, 50, 75),
  date_trouve = c("2024-01-01", "2024-02-01", "2024-03-01", "2024-03-15", "2024-04-01", "2024-05-01")
)

  # Test avec une seule variable de groupement
  expected_output_1 <- tibble::tibble(annee = c(2024), poids = c(825))
  expect_equal(weight_truffles_by(truffles, annee = lubridate::year(as.Date(date_trouve))), expected_output_1)
  
  # Test avec deux variables de groupement
  expected_output_2 <- tibble::tibble(idchene = c(1, 2, 3), annee = c(2024, 2024, 2024
), poids = c(250, 450, 125))
  expect_equal(weight_truffles_by(truffles, idchene, annee = lubridate::year(as.Date(date_trouve))), expected_output_2)
})
```
  
# get_info_chene_last_truffe
    
```{r function-get_info_chene_last_truffe}
#' Get Information about the Last Truffle Found on a Specific Oak Tree
#' 
#' This function retrieves information about the last truffle found on a specific oak tree.
#' 
#' @param dbtruffe A data frame containing information about truffles.
#' @param theidchene The ID of the oak tree.
#' @param filter_missing_info logical to filter truffle with missing data 
#' @importFrom dplyr filter mutate
#' @return A data frame containing information about the last truffle found on the specified oak tree.
#' 
#' @export
get_info_chene_last_truffe <- function(dbtruffe, theidchene, filter_missing_info = FALSE){


check_param(dbtruffe, "data.frame")
check_param(theidchene, "numeric")
check_param(filter_missing_info, "logical")
check_names_dataframe(c("poids","estimation", "idchene"), dbtruffe)


  if (!any(theidchene %in% dbtruffe$idchene)) {
    return(data.frame())
  }

if (isTRUE(filter_missing_info)){
  dbtruffe <- dbtruffe  |> 
  dplyr::filter(estimation == 1 | is.na(poids)) 
}

    truffe_chene <- dbtruffe |>
      filter(idchene == theidchene)  |> 
      filter(date_trouve == max(date_trouve)) |>
      dplyr::mutate(estim_js = dplyr::case_when(
          estimation == 1 ~ "checked = 'checked'", # TODO : deplace
          TRUE ~ ""
        ))

return(truffe_chene)
}
```
  
```{r example-get_info_chene_last_truffe}

dbtruffe <- data.frame(idchene = c(123, 123, 456, 789), 
                        estimation = c(1,0,1,0),
                        poids = c(NA, 5,10,100),
                        date_trouve = as.Date(c("2023-01-01", "2023-03-15", "2023-02-01", "2022-12-01")))

get_info_chene_last_truffe(dbtruffe = dbtruffe , theidchene = 123)
get_info_chene_last_truffe(dbtruffe = dbtruffe , theidchene = 123, filter_missing_info = TRUE)
```
  
```{r tests-get_info_chene_last_truffe}
test_that("get_info_chene_last_truffe works", {
  expect_true(inherits(get_info_chene_last_truffe, "function")) 

dbtruffe <- data.frame(idchene = c(123, 123, 456, 789), 
                        estimation = c(1,0,1,0),
                        poids = c(NA, 5,10,100),
                        date_trouve = as.Date(c("2023-01-01", "2023-03-15", "2023-02-01", "2022-12-01")))
   # Cas où l'arbre spécifié possède des truffes dans la base de données
  expect_equal(nrow(get_info_chene_last_truffe(dbtruffe, 123)), 1)
  expect_equal(get_info_chene_last_truffe(dbtruffe, 123)$idchene, 123)
  expect_equal(get_info_chene_last_truffe(dbtruffe, 123)$date_trouve, as.Date("2023-03-15"))
  
 
  # Cas où l'arbre spécifié n'existe pas dans la base de données
  expect_equal(nrow(get_info_chene_last_truffe(dbtruffe, 999)), 0)
})
```
  

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_get_info_chene_truffe.Rmd", check = FALSE, vignette_name = NA)
grkstyle::grk_style_pkg()
```
