---
title: "flat_utils_js.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# prepare_leaflet
    
```{r function-prepare_leaflet}
#' Prepare Leaflet Data
#' 
#' This function prepares data for Leaflet JavaScript visualization.
#' 
#' @param dbchene A data frame containing information about oak trees.
#' @param dbtruffe A data frame containing information about truffles.
#' @importFrom dplyr filter mutate distinct full_join
#' @return A list suitable for passing to Leaflet JavaScript for visualization.
#' 
#' @export
prepare_leaflet <- function(dbchene, dbtruffe){

t <- dbtruffe  |> 
dplyr::filter(estimation == 1 | is.na(poids))  |> 
dplyr::mutate(info_missing = 1) |> 
dplyr::distinct(idchene, info_missing)

c <- dbchene  |> 
dplyr::full_join(t, 
by = c("id" = "idchene"))

 data_prep <- lapply(
          1:nrow(c),
          function(i) {
            unname(as.list(as.character(c[i, ])))
          }
        )  

return(data_prep)

}
```
  
```{r example-prepare_leaflet}
dbchene <- data.frame(id = c(1, 2, 3),
                       chene_nom = c("Chene 1", "Chene 2", "Chene 3"))
dbtruffe <- data.frame(idchene = c(1, 2, 3),
                        estimation = c(1, 0, 1),
                        poids = c(10, 15, NA))
prepare_leaflet(dbchene, dbtruffe)
```
  
```{r tests-prepare_leaflet}
test_that("prepare_leaflet works", {
  expect_true(inherits(prepare_leaflet, "function")) 

dbchene <- data.frame(id = c(1, 2, 3),
                       chene_nom = c("Chene 1", "Chene 2", "Chene 3"))
dbtruffe <- data.frame(idchene = c(1, 2, 3),
                        estimation = c(1, 0, 1),
                        poids = c(10, 15, NA))

# Exécuter la fonction
  leaflet_data <- prepare_leaflet(dbchene, dbtruffe)
  
  # Vérifier le type de sortie
  expect_type(leaflet_data, "list")
  
  # Vérifier si la longueur de la liste est correcte
  expect_equal(length(leaflet_data), nrow(dbchene))


})
```
  

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_utils_js.Rmd", vignette_name = NA, check = FALSE)
```

