# WARNING - Generated by {fusen} from dev/flat_utils_js.Rmd: do not edit by hand

test_that("prepare_leaflet works", {
  expect_true(inherits(prepare_leaflet, "function"))

  dbchene <- data.frame(
    id = c(1, 2, 3),
    chene_nom = c("Chene 1", "Chene 2", "Chene 3")
  )
  dbtruffe <- data.frame(
    idchene = c(1, 2, 3),
    estimation = c(1, 0, 1),
    poids = c(10, 15, NA)
  )

  # Exécuter la fonction
  leaflet_data <- prepare_leaflet(dbchene, dbtruffe)

  # Vérifier le type de sortie
  expect_type(leaflet_data, "list")

  # Vérifier si la longueur de la liste est correcte
  expect_equal(length(leaflet_data$data_prep), nrow(dbchene))
})
