# WARNING - Generated by {fusen} from dev/flat_utils_db.Rmd: do not edit by hand

test_that("write_db_new_truffe works", {
  conn <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
  
  # Création de la table truffe dans la base de données
  DBI::dbWriteTable(
    conn,
    "truffe",
    data.frame(
      id_truffe = character(),
      id_chene = numeric(),
      date_trouve = numeric(),
      poids = numeric(),
      commentaires = character()
    )
  )
  
  # Écrire une nouvelle truffe dans la base de données
  id_chene <- 1
  date_trouvee <- "2024-03-08"
  poids <- 50
  comment <- "Truffe fraîchement trouvée"
  write_db_new_truffe(conn, id_chene, date_trouvee, poids, comment, digest_ = date_trouvee)
  
  # Vérifier si la truffe a été correctement ajoutée à la base de données
  expected_output <-
    data.frame(
      id_truffe = digest::digest(date_trouvee),
      id_chene = 1,
      date_trouve = 19790,
      poids = 50,
      commentaires = "Truffe fraîchement trouvée"
    )
  expect_equal(DBI::dbReadTable(conn, "truffe"), expected_output)
})
