# WARNING - Generated by {fusen} from dev/flat_utils_db.Rmd: do not edit by hand

test_that("connect_db works", {
  conn <- connect_db()

  # Vérifier que la connexion est valide
  expect_s4_class(conn, "SQLiteConnection")
})
