# WARNING - Generated by {fusen} from dev/flat_get_info_chene_truffe.Rmd: do not edit by hand

test_that("weight_truffles_by works", {
truffles <- data.frame(
  idchene = c(1, 1, 2, 2, 3, 3),
  poids = c(100, 150, 200, 250, 50, 75),
  date_trouve = c("2024-01-01", "2024-02-01", "2024-03-01", "2024-03-15", "2024-04-01", "2024-05-01")
)

  # Test avec une seule variable de groupement
  expected_output_1 <- tibble::tibble(annee = c(2024), poids = c(825))
  expect_equal(weight_truffles_by(truffles, annee), expected_output_1)
  
  # Test avec deux variables de groupement
  expected_output_2 <- tibble::tibble(idchene = c(1, 2, 3), annee = c(2024, 2024, 2024
), poids = c(250, 450, 125))
  expect_equal(weight_truffles_by(truffles, idchene, annee), expected_output_2)
})
