# WARNING - Generated by {fusen} from dev/flat_get_info_chene_truffe.Rmd: do not edit by hand

test_that("get_info_chene works", {
  
  
  dbchene <- data.frame(
    id = c(1, 2, 3),
    type = c("Chêne vert", "Chêne rouvre", "Chêne pédonculé"),
    date_plantation = c("2020-01-01", "2018-03-15", "2019-06-20")
  )
  
  # Test quand le chêne n'existe pas dans la base de données
  expect_equal(get_info_chene(dbchene, 4),
               list(
                 type = character(0),
                 date_plantation = structure(numeric(0), class = "Date")
               ))
  
  # Test quand le chêne existe dans la base de données
  expect_equal(get_info_chene(dbchene, 2),
               list(type = "Chêne rouvre", date_plantation = as.Date("2018-03-15")))
  
})
