# WARNING - Generated by {fusen} from dev/flat_utils_db.Rmd: do not edit by hand

#' connect_db
#' 
#' To connect to the database available in the {truffles} package
#' 
#' @param dbname name of db available in inst/
#' @importFrom RSQLite SQLite
#' @importFrom DBI dbConnect
#' @return NULL
#' 
#' @export
#' @examples
#' connect_db()
connect_db <- function(dbname = "chenes_truffe.sqlite"){
    conn <- dbConnect(SQLite(), 
                      system.file(dbname, package = "truffles"))
    return(conn)
}
