# WARNING - Generated by {fusen} from dev/flat_utils_db.Rmd: do not edit by hand

#' Title
#' 
#' Description
#' 
#' @param dbname name of db available in inst/
#' @importFrom RSQLite SQLite
#' @importFrom DBI dbConnect
#' @return
#' 
#' @export
#' @examples
#' connect_db()
connect_db <- function(dbname = "chenes_truffe.sqlite"){
    conn <- dbConnect(SQLite(), 
                      system.file(dbname, package = "truffe"))
    return(conn)
}
