# WARNING - Generated by {fusen} from dev/flat_get_info_chene_truffe.Rmd: do not edit by hand

#' Get information about truffles associated with an oak tree
#'
#' This function retrieves information about truffles associated with a specific oak tree
#' based on the oak tree's ID from the provided truffle database.
#'
#' @param dbtruffe Database containing information about truffles.
#' @param theidchene ID of the oak tree for which information about associated truffles
#' is to be retrieved.
#'
#' @return A list containing information about truffles associated with the oak tree,
#' including the total weight, date of the last truffle found, and any comments.
#'
#' @importFrom dplyr filter summarise pull
#' @export
#'
#' @examples
#' conn <- connect_db()
#' truffe <- DBI::dbReadTable(conn, name = "truffe")
#'
#' get_info_chene_truffe(dbtruffe = truffe, theidchene = "119")
#' DBI::dbDisconnect(conn)
get_info_chene_truffe <- function(dbtruffe, theidchene) {
  truffe_chene <- dbtruffe |>
    filter(idchene == theidchene)

  if (nrow(truffe_chene) == 0) {
    return(list(
      poids_tot = 0,
      derniere_truffe = "-",
      comments = "-"
    ))
  }

  poids_tot <- truffe_chene |>
    summarise(poids_tot = sum(poids, na.rm = TRUE)) |>
    pull(poids_tot)

  derniere_truffe <- truffe_chene |>
    summarise(date_trouve = as.Date(max(date_trouve, na.rm = TRUE))) |>
    pull(date_trouve)

  comments <-
    paste(
      paste(
        as.Date(truffe_chene$date_trouve),
        truffe_chene$commentaires,
        sep = " : "
      ),
      collapse = "<br>"
    )

  return(list(
    poids_tot = poids_tot,
    derniere_truffe = derniere_truffe,
    comments = comments
  ))
}
