# WARNING - Generated by {fusen} from dev/flat_get_info_chene_truffe.Rmd: do not edit by hand

#' Title
#'
#' Description
#'
#' @param dbchene dbchene TOCOMPLETE
#' @param idchene idchene TOCOMPLETE
#'
#'
#' @importFrom dplyr filter
#' @return a list
#'
#' @export
#' @examples
#' conn <- DBI::dbConnect(RSQLite::SQLite(), system.file("chenes_truffe.sqlite", package = "truffles"))
#' chene <- DBI::dbReadTable(conn, name = "chenes_feularde")
#'
#' get_info_chene(dbchene = chene, idchene = "chenes162")
#' DBI::dbDisconnect(conn)
#'
get_info_chene <- function(dbchene, idchene) {
  chene <- dbchene |>
    filter(id == idchene)

  return(list(
    type = chene$type,
    date_plantation = as.Date(chene$date_plantation)
  ))
}
