# WARNING - Generated by {fusen} from dev/flat_get_info_chene_truffe.Rmd: do not edit by hand

#' Get Information about the Last Truffle Found on a Specific Oak Tree
#'
#' This function retrieves information about the last truffle found on a specific oak tree.
#'
#' @param dbtruffe A data frame containing information about truffles.
#' @param theidchene The ID of the oak tree.
#' @importFrom dplyr filter
#' @return A data frame containing information about the last truffle found on the specified oak tree.
#'
#' @export
#' @examples
#'
#' dbtruffe <- data.frame(
#'   idchene = c(123, 123, 456, 789),
#'   date_trouve = as.Date(c("2023-01-01", "2023-03-15", "2023-02-01", "2022-12-01"))
#' )
#' get_info_chene_last_truffe(dbtruffe = dbtruffe, theidchene = 123)
get_info_chene_last_truffe <- function(dbtruffe, theidchene) {
  if (isFALSE("idchene" %in% names(dbtruffe))) {
    stop("The column idchene is missing")
  }
  if (!any(theidchene %in% dbtruffe$idchene)) {
    return(data.frame())
  }
  truffe_chene <- dbtruffe |>
    filter(idchene == theidchene) |>
    filter(date_trouve == max(date_trouve))

  return(truffe_chene)
}
