# WARNING - Generated by {fusen} from dev/flat_get_info_chene_truffe.Rmd: do not edit by hand

#' Title
#'
#' Description
#'
#' @return
#'
#' @export
#' @examples
#' conn <- DBI::dbConnect(RSQLite::SQLite(), system.file("chenes_truffe.sqlite", package = "truffles"))
#' chene <- DBI::dbReadTable(conn, name = "chenes_feularde")
#' truffe <- DBI::dbReadTable(conn, name = "truffe")
#'
#' get_info(dbchene = chene, dbtruffe = truffe, theidchene = "162")
#' DBI::dbDisconnect(conn)
get_info <- function(dbchene, dbtruffe, theidchene) {
  resultat <- list(
    chene = get_info_chene(dbchene = dbchene, theidchene = theidchene),
    truffes = get_info_chene_truffe(dbtruffe = dbtruffe, theidchene = theidchene)
  )

  return(resultat)
}
