# WARNING - Generated by {fusen} from dev/flat_get_info_chene_truffe.Rmd: do not edit by hand

#' get_info_chene_truffe Title
#'
#' @param dbtruffe dbtruffe TOCOMPLETE
#' @param idchene idchene TOCOMPLETE
#'
#' @return a list
#' @importFrom dplyr filter summarise pull
#' @export
#'
#' @examples
#' conn <- connect_db()
#' truffe <- DBI::dbReadTable(conn, name = "truffe")
#'
#' get_info_chene_truffe(dbtruffe = truffe, idchene = "chene162")
#' DBI::dbDisconnect(conn)
get_info_chene_truffe <- function(dbtruffe, idchene) {
  truffe_chene <- dbtruffe |>
    filter(id_chene == idchene)

  if (nrow(truffe_chene) == 0) {
    return(list(
      poids_tot = 0,
      derniere_truffe = "-"
    ))
  }

  poids_tot <- truffe_chene |>
    summarise(poids_tot = sum(poids, na.rm = TRUE)) |>
    pull(poids_tot)

  derniere_truffe <- truffe_chene |>
    summarise(date_trouve = as.Date(max(date_trouve, na.rm = TRUE))) |>
    pull(date_trouve)

  return(list(
    poids_tot = poids_tot,
    derniere_truffe = derniere_truffe
  ))
}
