# WARNING - Generated by {fusen} from dev/flat_get_info_chene_truffe.Rmd: do not edit by hand

#' Get information about an oak tree
#'
#' This function retrieves information about a specific oak tree based on its ID
#' from the provided oak tree database.
#'
#' @param dbchene Database containing information about oak trees.
#' @param theidchene ID of the oak tree for which information is to be retrieved.
#'
#' @return A list containing information about the oak tree, including its type and
#' date of plantation.
#'
#' @importFrom dplyr filter
#' @return a list
#'
#' @export
#' @examples
#' conn <- DBI::dbConnect(RSQLite::SQLite(), system.file("chenes_truffe.sqlite", package = "truffles"))
#' chene <- DBI::dbReadTable(conn, name = "chenes_feularde")
#'
#' get_info_chene(dbchene = chene, theidchene = "162")
#' DBI::dbDisconnect(conn)
#'
get_info_chene <- function(dbchene, theidchene) {
  chene <- dbchene |>
    filter(id == theidchene)

  return(list(
    type = chene$type,
    date_plantation = as.Date(chene$date_plantation)
  ))
}
