# WARNING - Generated by {fusen} from dev/flat_get_info_chene_truffe.Rmd: do not edit by hand

#' Title
#' 
#' Description
#' 
#' @param truffles database
#'
#' @return a dataframe
#' @importFrom dplyr mutate group_by summarise
#' @importFrom lubridate year
#' @export
#' @examples
#' conn <- connect_db()
#' truffes <- DBI::dbReadTable(conn, name = "truffe")
#'
#' truffles_by_year(truffes)
truffles_by_year <- function(truffles) {
  truffles |> 
    mutate(annee = year(as.Date(date_trouve))) |>  
    group_by(annee) |> 
    summarise(poids = sum(poids))
}
