# WARNING - Generated by {fusen} from dev/flat_utils_db.Rmd: do not edit by hand

#' write_db_new_truffe
#' 
#' Description
#'
#' @param conn a connection to database
#' @param theidchene TOCOMPLETE
#' @param date_trouvee TOCOMPLETE 
#' @param poids TOCOMPLETE
#' @param comment TOCOMPLETE
#' @param digest_ TOCOMPLETE
#'
#' @importFrom digest digest
#' @importFrom DBI dbAppendTable
#' @return NULL
#' 
#' @export
#' @examples
#' # write_db_new_truffe(theidchene = "chene")
write_db_new_truffe <-
  function(conn = connect_db(), theidchene, date_trouvee, poids, comment, digest_ = Sys.time()) {
    
  idtruffe = digest(digest_)
    
  add_truffe <- data.frame(
  idtruffe = idtruffe,
  idchene = theidchene,
  date_trouve = as.Date(date_trouvee),
  poids = poids,
  commentaires = comment
)
  
  dbAppendTable(conn, "truffe", add_truffe)
  }
