# WARNING - Generated by {fusen} from dev/flat_utils_db.Rmd: do not edit by hand

#' Write new truffle data to the database
#'
#' This function writes new truffle data to the specified database table.
#'
#' @param conn A connection to the database.
#' @param theidchene The ID of the oak tree (chêne) where the truffle was found.
#' @param date_trouvee The date the truffle was found.
#' @param poids The weight of the truffle in grams.
#' @param estimation logical indicating whether the weight was estimated or not.
#' @param comment Any additional comments related to the truffle.
#' @param digest_ The digest of the truffle.
#' @param date_comment the date of the comment (Sys.Date() by default)
#'
#' @importFrom digest digest
#' @importFrom DBI dbAppendTable
#' @return NULL
#'
#' @export
#' @examples
#' # write_db_new_truffe(theidchene = "chene")
write_db_new_truffe <-
  function(conn = connect_db(), theidchene, date_trouvee, poids, estimation, comment, digest_ = Sys.time(), date_comment = Sys.Date()) {
    idtruffe <- digest(digest_)

    add_truffe <- data.frame(
      idtruffe = idtruffe,
      idchene = theidchene,
      date_trouve = as.Date(date_trouvee),
      poids = poids,
      estimation = estimation,
      commentaires = paste(date_comment, comment, sep = " : ")
    )

    dbAppendTable(conn, "truffe", add_truffe)
    message("WRITING in DB truffe")
  }
