# WARNING - Generated by {fusen} from dev/flat_utils_db.Rmd: do not edit by hand

#' write_db_new_truffe
#'
#' Description
#' @importFrom digest digest
#' @importFrom DBI dbAppendTable
#' @return NULL
#'
#' @export
#' @examples
#' # write_db_new_truffe(id_chene = "chene")
write_db_new_truffe <-
  function(conn = connect_db(), id_chene, date_trouvee, poids) {
    idtruffe <- digest(Sys.time())

    add_truffe <- data.frame(
      id_truffe = idtruffe,
      id_chene = id_chene,
      date_trouve = as.Date(date_trouvee),
      poids = poids
    )

    dbAppendTable(conn, "truffe", add_truffe)
  }
