name: Connect to DB every 5 days

on: 
  schedule:
    - cron: '0 6 */5 * *' # Tous les 5 jours à 6h du matin UTC

jobs:
  connect-db:
    runs-on: windows-latest

    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PWD: ${{ secrets.DB_PWD }}
      DB_HOST: ${{ secrets.DB_HOST }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages("remotes")'
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'


      - name: Install truffles
        run: |
          Rscript -e 'remotes::install_local(".", upgrade = "never")'

      - name: check env
        run: |
          Rscript -e 'substr(Sys.getenv("DB_USER"), start = 1, stop = 3 )'
          Rscript -e 'substr(Sys.getenv("DB_PWD"), start = 1, stop = 3 )'
          Rscript -e 'substr(Sys.getenv("DB_HOST"), start = 1, stop = 3 )'

      - name: Test DB connection
        run: |
          Rscript -e 'library(truffles); con <- connect_db(); write_db_new_truffle(conn = con, theidoak = 1, date_found = Sys.Date(), weight = 25, estimation = 1, comment = "tosupp_for_CI"); DBI::dbExecute(con, "DELETE FROM truffe WHERE comment = $1", params = list("tosupp_for_CI")); DBI::dbDisconnect(con)'

